
const db = require('./database');

const products = [
  {
    "id": 11,
    "name": "L'Essentiel - Base Pure en Vrac (30g)",
    "description": "Notre mélange signature. Feuilles de framboisier sélectionnées à la main, séchées à l'air libre. Douces, discrètes, naturelles. Roulez votre propre rituel — sans tabac, sans nicotine. Juste le geste, purifié.",
    "price": 8.9,
    "image_url": "/images/pochon_kraft_noir.png",
    "stock": 100,
    "tagline": "Le Rituel",
    "type": "secondary",
    "badge": "100% naturel",
    "created_at": "2026-04-28 10:24:11",
    "categorie": "vrac",
    "short_description": "Notre mélange signature. Feuilles de framboisier sélectionnées à la main, séchées à l'air libre. Douces, discrètes, naturelles. Roulez votre propre rituel — sans tabac, sans nicotine. Juste le geste, purifié.",
    "composition": "100% Feuilles de framboisier (Rubus idaeus) - Cultive en France",
    "mode_utilisation": "Utiliser comme base de roulage avec des feuilles à cigarettes et un filtre.",
    "weight_grams": 30,
    "width_mm": 100,
    "height_mm": 20,
    "depth_mm": 70,
    "status": "published",
    "is_active": 1,
    "slug": "lessentiel-base-pure-vrac",
    "unit_label": "gramme",
    "price_per_unit": 0.2966666666666667,
    "is_best_value": 0,
    "tags": "[\"substitut\"]",
    "reference_market_price": 18.5,
    "images": "[\"/images/pochon_kraft_noir.png\"]",
    "competitor_price": 14.9,
    "competitor_label": "Plantes à rouler premium du marché (30g)",
    "tagline_subtitle": "Feuilles de framboisier séchées à rouler — alternative tabac 100% naturelle.",
    "use_cases": "[\"Remplace le tabac dans un joint\",\"Pour rouleurs de clopes naturelles\",\"Transition tabac → plantes\",\"Mélange CBD sans nicotine\"]",
    "weight_g": 80,
    "height_cm": 5,
    "width_cm": 9,
    "length_cm": 14,
    "weight": 50,
    "thickness_mm": 15
  },
  {
    "id": 12,
    "name": "L'Instant - Pack de Pré-roulés (x3)",
    "description": "Le format test. Trois cônes pré-remplis pour découvrir Doiryshop sans engagement. Idéal pour un premier essai ou un cadeau.",
    "price": 6.9,
    "image_url": "/images/etui_preroules.png",
    "stock": 80,
    "tagline": "Le Rituel",
    "type": "secondary",
    "badge": "Pret a l'emploi",
    "created_at": "2026-04-28 10:24:11",
    "categorie": "pre-roules",
    "short_description": "Le format test. Trois cônes pré-remplis pour découvrir Doiryshop sans engagement. Idéal pour un premier essai ou un cadeau.",
    "composition": "Melange de feuilles de framboisier et molene - Cones en papier non blanchi",
    "mode_utilisation": "Pret a consommer. Allumer et savourer.",
    "weight_grams": 15,
    "width_mm": 110,
    "height_mm": 25,
    "depth_mm": 80,
    "status": "published",
    "is_active": 1,
    "slug": "linstant-pre-roules-x3",
    "unit_label": "pre-roule",
    "price_per_unit": 2.3,
    "is_best_value": 0,
    "tags": "[\"substitut\"]",
    "reference_market_price": 2.5,
    "images": "[\"/images/etui_preroules.png\"]",
    "competitor_price": 2.9,
    "competitor_label": "Prix d'un pré-roulé sans tabac en boutique physique",
    "tagline_subtitle": "3 pré-roulés aux plantes, sans tabac ni nicotine — prêts à l'emploi.",
    "use_cases": "[\"Prêt à consommer\",\"Découverte sans engagement\",\"Zéro préparation\"]",
    "weight_g": 30,
    "height_cm": 5,
    "width_cm": 8,
    "length_cm": 12,
    "weight": 50,
    "thickness_mm": 20
  },
  {
    "id": 13,
    "name": "L'Instant - Pack de Pré-roulés (x5)",
    "description": "Le format des convaincus. Cinq cônes pré-remplis, prêts à l'emploi. Glissez-en un dans votre poche le matin, sortez-le le soir. Propre. Discret. Naturel. Notre best-seller.",
    "price": 9,
    "image_url": "/images/etui_preroules.png",
    "stock": 100,
    "tagline": "Le Rituel",
    "type": "primary",
    "badge": "Meilleur choix",
    "created_at": "2026-04-28 10:24:11",
    "categorie": "pre-roules",
    "short_description": null,
    "composition": null,
    "mode_utilisation": null,
    "weight_grams": 25,
    "width_mm": 110,
    "height_mm": 25,
    "depth_mm": 80,
    "status": "published",
    "is_active": 1,
    "slug": "linstant-pre-roules-x5",
    "unit_label": "pre-roule",
    "price_per_unit": 1.8,
    "is_best_value": 0,
    "tags": "[\"pre-roules\"]",
    "reference_market_price": null,
    "images": "[\"/images/etui_preroules.png\"]",
    "competitor_price": 2.9,
    "competitor_label": "Prix d'un pré-roulé sans tabac en boutique physique",
    "tagline_subtitle": "5 pré-roulés aux plantes — format quotidien, zéro préparation.",
    "use_cases": "[\"Format quotidien\",\"Zéro tabac zéro préparation\",\"Best-seller\"]",
    "weight_g": 50,
    "height_cm": 5,
    "width_cm": 8,
    "length_cm": 12,
    "weight": 50,
    "thickness_mm": 22
  },
  {
    "id": 14,
    "name": "Le Coffret Transition - Kit de Roulage",
    "description": "✦ CE QUE ÇA T'APPORTE\n• Tout ce qu'il faut pour rouler tes propres cigarettes de plantes dès ce soir\n• Zéro tabac, zéro nicotine — le geste de roulage intact\n• Format complet : tu n'as besoin de rien acheter en plus\n\n✦ CE QUE C'EST\n• Pochon de plantes à rouler 30g (L'Essentiel — feuilles de framboisier)\n• Feuilles à rouler chanvre non blanchi (x33 slim 110mm)\n• Filtres carton bio (x50)\n• Carte rituel — guide de dosage et de roulage",
    "price": 19.9,
    "image_url": "/images/coffret_complet_flatlay.png",
    "stock": 50,
    "tagline": "Le Rituel",
    "type": "secondary",
    "badge": "Coffret cadeau",
    "created_at": "2026-04-28 10:24:11",
    "categorie": "kits",
    "short_description": "Tout le kit pour rouler sans tabac ni nicotine.",
    "composition": "100% Feuilles de framboisier + accessoires roulage (papier non blanchi, filtres carton)",
    "mode_utilisation": "Versez le contenu du pochon dans une feuille a rouler, ajoutez un filtre et roulez.",
    "weight_grams": 120,
    "width_mm": 180,
    "height_mm": 50,
    "depth_mm": 140,
    "status": "published",
    "is_active": 1,
    "slug": "coffret-transition-kit-roulage",
    "unit_label": "coffret",
    "price_per_unit": 19.9,
    "is_best_value": 0,
    "tags": "[\"substitut\"]",
    "reference_market_price": null,
    "images": "[\"/images/coffret_complet_flatlay.png\"]",
    "competitor_price": 28.9,
    "competitor_label": "Si acheté séparément en boutique",
    "tagline_subtitle": "Tout pour rouler vos propres cigarettes de plantes dès ce soir.",
    "use_cases": "[\"Arrêter le tabac progressivement\",\"Kit complet débutant\",\"Je roule moi-même\"]",
    "weight_g": 250,
    "height_cm": 5,
    "width_cm": 15,
    "length_cm": 20,
    "weight": 50,
    "thickness_mm": 40
  },
  {
    "id": 15,
    "name": "L'Élixir Nocturne - Infusion en Vrac (50g)",
    "description": "Valériane, mélisse, passiflore, aubépine. Quatre plantes, un seul but : accompagner le moment de détente. Infusez 10 minutes, laissez faire. Le sommeil ne se force pas — il s'accompagne.",
    "price": 12.9,
    "image_url": "/images/boite_infusion_kraft.png",
    "stock": 80,
    "tagline": "L'Apaisement",
    "type": "secondary",
    "badge": "Detente nocturne",
    "created_at": "2026-04-28 10:24:11",
    "categorie": "vrac",
    "short_description": "Valériane, mélisse, passiflore, aubépine. Quatre plantes, un seul but : accompagner le moment de détente. Infusez 10 minutes, laissez faire. Le sommeil ne se force pas — il s'accompagne.",
    "composition": "Valeriane, melisse, passiflore, aubepine - Toutes plantes cultivees en Europe",
    "mode_utilisation": "1 cuillere a cafe (3-5g) dans 250ml d'eau a 90C. Infuser 10 minutes couvert.",
    "weight_grams": 50,
    "width_mm": 120,
    "height_mm": 30,
    "depth_mm": 90,
    "status": "published",
    "is_active": 1,
    "slug": "elixir-nocturne-infusion-vrac",
    "unit_label": "gramme",
    "price_per_unit": 0.258,
    "is_best_value": 0,
    "tags": "[\"tisanes\"]",
    "reference_market_price": 1.5,
    "images": "[\"/images/boite_infusion_kraft.png\"]",
    "competitor_price": 16.5,
    "competitor_label": "Prix herboristerie France (infusion sommeil 50g)",
    "tagline_subtitle": "Infusion valériane-passiflore pour s'endormir naturellement — 50g en vrac.",
    "use_cases": "[\"Rituel du soir\",\"Aide à l'endormissement\",\"Alternative sans fumée\"]",
    "weight_g": 120,
    "height_cm": 5,
    "width_cm": 10,
    "length_cm": 15,
    "weight": 50,
    "thickness_mm": 25
  },
  {
    "id": 16,
    "name": "L'Élixir Nocturne - Boîte de 20 Infusettes",
    "description": "20 nuits apaisées, une boîte. Pratique au bureau, discret en voyage, puissant à la maison. Votre dose de sérénité, toujours à portée de main.",
    "price": 13.9,
    "image_url": "/images/boite_infusion_kraft.png",
    "stock": 100,
    "tagline": "L'Apaisement",
    "type": "primary",
    "badge": "Meilleur choix",
    "created_at": "2026-04-28 10:24:11",
    "categorie": "tisanes",
    "short_description": "20 nuits apaisées, une boîte. Pratique au bureau, discret en voyage, puissant à la maison. Votre dose de sérénité, toujours à portée de main.",
    "composition": "Valeriane, melisse, passiflore, aubepine - Sachets biodegradables",
    "mode_utilisation": "1 sachet dans 250ml d'eau chaude. Infuser 8 a 10 minutes.",
    "weight_grams": 60,
    "width_mm": 140,
    "height_mm": 40,
    "depth_mm": 110,
    "status": "published",
    "is_active": 1,
    "slug": "elixir-nocturne-boite-20-sachets",
    "unit_label": "sachet",
    "price_per_unit": 0.6950000000000001,
    "is_best_value": 1,
    "tags": "[\"tisanes\"]",
    "reference_market_price": 1.5,
    "images": "[\"/images/boite_infusion_kraft.png\"]",
    "competitor_price": 1.2,
    "competitor_label": "Prix d'un sachet de tisane en grande surface",
    "tagline_subtitle": "20 sachets de tisane apaisante du soir — pour 20 nuits de détente.",
    "use_cases": "[\"20 nuits apaisées\",\"Pratique au bureau\",\"Discret en voyage\"]",
    "weight_g": 100,
    "height_cm": 5,
    "width_cm": 11,
    "length_cm": 15,
    "weight": 50,
    "thickness_mm": 25
  },
  {
    "id": 17,
    "name": "L'Élixir Nocturne - Boîte de 10 Infusettes",
    "description": "Le format découverte. Dix sachets pour tester L'Élixir Nocturne sans engagement. Idéal en cadeau ou pour un essai.",
    "price": 7.9,
    "image_url": "/images/boite_infusion_kraft.png",
    "stock": 60,
    "tagline": "L'Apaisement",
    "type": "secondary",
    "badge": "Decouverte",
    "created_at": "2026-04-28 10:24:11",
    "categorie": "tisanes",
    "short_description": "Le format découverte. Dix sachets pour tester L'Élixir Nocturne sans engagement. Idéal en cadeau ou pour un essai.",
    "composition": "Valeriane, melisse, passiflore, aubepine - Sachets biodegradables",
    "mode_utilisation": "1 sachet dans 250ml d'eau chaude. Infuser 8 a 10 minutes.",
    "weight_grams": 35,
    "width_mm": 140,
    "height_mm": 40,
    "depth_mm": 110,
    "status": "published",
    "is_active": 1,
    "slug": "elixir-nocturne-boite-10-sachets",
    "unit_label": "sachet",
    "price_per_unit": 0.79,
    "is_best_value": 0,
    "tags": "[\"tisanes\"]",
    "reference_market_price": 1.5,
    "images": "[\"/images/boite_infusion_kraft.png\"]",
    "competitor_price": 1.2,
    "competitor_label": "Prix d'un sachet de tisane en grande surface",
    "tagline_subtitle": "10 sachets pour tester la tisane du soir sans engagement.",
    "use_cases": "[\"Format découverte\",\"Idéal en cadeau\",\"Sans engagement\"]",
    "weight_g": 60,
    "height_cm": 5,
    "width_cm": 10,
    "length_cm": 14,
    "weight": 50,
    "thickness_mm": 20
  },
  {
    "id": 18,
    "name": "Le Coffret Sérénité - Kit Détente",
    "description": "✦ CE QUE ÇA T'APPORTE\n• Un rituel complet pour débrancher et décompresser le soir\n• Idéal en cadeau ou pour soi — sans nicotine, sans artifice\n• Cinq éléments soigneusement sélectionnés, utilisables ensemble ou séparément\n\n✦ CE QUE C'EST\n• Infusion Élixir Nocturne en vrac 50g\n  (valériane, passiflore, mélisse, aubépine)\n• 10 sachets tisane réutilisables lavables\n• 1 cuillère doseuse en bois\n• 1 carte rituel du soir",
    "price": 27.9,
    "image_url": "/images/coffret-serenite-placeholder.svg",
    "stock": 30,
    "tagline": "L'Apaisement",
    "type": "secondary",
    "badge": "Coffret cadeau",
    "created_at": "2026-04-28 10:24:11",
    "categorie": "kits",
    "short_description": "Un rituel complet pour débrancher le soir.",
    "composition": "Melange plantes apaisantes + bougie soja naturelle + livret papier recycle",
    "mode_utilisation": "Allumez la bougie, preparez votre infusion et laissez le calme s'installer.",
    "weight_grams": 300,
    "width_mm": 220,
    "height_mm": 70,
    "depth_mm": 180,
    "status": "published",
    "is_active": 1,
    "slug": "coffret-serenite-kit-detente",
    "unit_label": "coffret",
    "price_per_unit": 27.9,
    "is_best_value": 0,
    "tags": "[\"tisanes\"]",
    "reference_market_price": null,
    "images": "[\"/images/coffret_complet_flatlay.png\"]",
    "competitor_price": 45,
    "competitor_label": "Si acheté séparément en boutique bien-être",
    "tagline_subtitle": "Coffret cadeau détente — infusion, bougie et rituel du soir réunis.",
    "use_cases": "[\"Cadeau détente idéal\",\"Rituel du soir complet\",\"Pour soi ou à offrir\"]",
    "weight_g": 350,
    "height_cm": 5,
    "width_cm": 18,
    "length_cm": 22,
    "weight": 50,
    "thickness_mm": 50
  }
];
const coupons = [
  {
    "id": 4,
    "code": "BIENVENUE10",
    "type": "pourcentage",
    "valeur": 10,
    "date_expiration": "2030-10-23T23:59:59",
    "nombre_utilisations_max": 300,
    "nombre_utilisations_actuel": 0,
    "actif": 1,
    "date_creation": "2026-05-01 20:16:31"
  },
  {
    "id": 5,
    "code": "BIENVENUE11",
    "type": "montant_fixe",
    "valeur": 10,
    "date_expiration": "2030-10-23T23:59:59",
    "nombre_utilisations_max": 200,
    "nombre_utilisations_actuel": 0,
    "actif": 1,
    "date_creation": "2026-05-01 20:17:55"
  }
];

function seedDatabase() {
  db.get('SELECT COUNT(*) as count FROM products', (err, row) => {
    if (err) {
      console.error('Erreur verification produits:', err);
      return;
    }
    if (row && row.count === 0) {
      console.log('Table produits vide, insertion des produits de base...');
      
      const stmt = db.prepare(`
        INSERT INTO products (
          id, name, description, price, image_url, stock, tagline, type, badge,
          created_at, categorie, short_description, composition, mode_utilisation,
          weight_grams, width_mm, height_mm, depth_mm, status, is_active, slug,
          unit_label, price_per_unit, is_best_value, tags, reference_market_price,
          images, competitor_price, competitor_label, tagline_subtitle, use_cases,
          weight_g, height_cm, width_cm, length_cm, weight, thickness_mm
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `);

      products.forEach((p) => {
        stmt.run(
          p.id, p.name, p.description, p.price, p.image_url, p.stock, p.tagline, p.type, p.badge,
          p.created_at, p.categorie, p.short_description, p.composition, p.mode_utilisation,
          p.weight_grams, p.width_mm, p.height_mm, p.depth_mm, p.status, p.is_active, p.slug,
          p.unit_label, p.price_per_unit, p.is_best_value, p.tags, p.reference_market_price,
          p.images, p.competitor_price, p.competitor_label, p.tagline_subtitle, p.use_cases,
          p.weight_g, p.height_cm, p.width_cm, p.length_cm, p.weight, p.thickness_mm
        );
      });
      stmt.finalize();
      console.log('Produits inseres avec succes.');
    } else {
      console.log('Produits deja presents, on ne fait rien.');
    }
  });

  // Coupons
  db.get('SELECT name FROM sqlite_master WHERE type="table" AND name="coupons"', (err, table) => {
    if (table) {
      db.get('SELECT COUNT(*) as count FROM coupons', (err, row) => {
        if (row && row.count === 0 && coupons.length > 0) {
          console.log('Table coupons vide, insertion...');
          const stmt = db.prepare('INSERT INTO coupons (code, type, valeur, nombre_utilisations_max, actif) VALUES (?, ?, ?, ?, ?)');
          coupons.forEach(c => {
            stmt.run(c.code, c.type, c.valeur, c.nombre_utilisations_max, c.actif);
          });
          stmt.finalize();
        }
      });
    }
  });
}

module.exports = { seedDatabase };
